import Foundation

/// Таблицы допустимых буквосочетаний (триграмм с маркером начала слова «^») для русского
/// и английского. СГЕНЕРИРОВАНО `macos/tools/gen_instant_tables.py` по частотному корпусу
/// OpenSubtitles-2018 (hermitdave/FrequencyWords, 50k слов на язык); порог — суммарная
/// взвешенная частота сочетания ≥ 1e-07 от корпуса: он отсекает опечатки и
/// иноязычный мусор корпуса, сохраняя живые редкие сочетания. Руками не править.
///
/// Формат: битовая маска, индекс = c0*N² + c1*N + c2, где N = алфавит+1, код 0 — «начало слова».
/// Размер: ru 4913 Б, en 2461 Б — проверка сочетания это сдвиг и AND, никакого
/// словаря и никакого XPC (в отличие от NSSpellChecker), поэтому детект можно гнать на каждую
/// нажатую букву, не рискуя фризом event tap.
enum NGramTables {
    static let ruAlphabet = Array("абвгдеёжзийклмнопрстуфхцчшщъыьэюя")
    static let enAlphabet = Array("abcdefghijklmnopqrstuvwxyz")

    static let ru = NGramSet(alphabet: ruAlphabet, base64: ruBase64)
    static let en = NGramSet(alphabet: enAlphabet, base64: enBase64)

    private static let ruBase64 = """
    AAAAAPj9/xsqTn5Cvv/9//3q5DWgKd/3gM//79kyAS4EAPrFJQC5kdcA6Wf/y5gQYQNA3uS/4lmXp5IvT94qvrt5Hfg+//8P
    CJP3m+9cmEO6//3//dqUr+j7//8/bkTSCpw2XQkwahY0IAmX3QKjTH9DiDABAQAAAAAAAAACAAAAAAAAj743IT71ngDweT8q
    BgAAAIAAPCMA7rc9YOrT97ytRl4CgP/9W9k8cpYHAABBECBfXQKA333JHDziFATo2f8d7FffV4h93T7Y7vbvYfpf9r9PAs8A
    gBD9j9n+9v/nq9P/n6tE3zc+jS2XIVKkbSIokdcCYUQBEoBYZQgQwvQ1QAkRgAAAAAAAAAAAAAAAAAAAAIAwAAAAgIEAAjzm
    AAAAAADw+fMfLESSAIAQAQAAAAABAAARgACk9+vRAEggAQBAAAAACAAEgOD3//UwAAAAAEIEIQAIE4QArwQQAIAQQQmM/v++
    BgMBAAAgTBACvhBMDIAABAQA+O3zGw4AAAAAAEAAAAIAAAAAEAAAAEQAAIAQIQgAwAAAAGLhYyoADJABMAE+BQAgJBwAAglA
    KAAAAAAA3z7/wwAkAQAAEySACAQCAoASQQkIfPseTwKIURAAQAAAgA9pAYh+/90PAwAAACBEUgKAMEEAwEKEaSAKE4SA7P//
    +7AQSQkAwoQhIArDSQIsQFACshgepsNAAIAAAAAUACAEEAKCEEEIAEIEIAAAEAAAAAQAAADfv6+BwAQYIAOgAgAAAAAAIMgs
    BgIAAAAA8L1/HgxEAACAEEEAAEAkCQAIARAAgOb/ASAAKAEAAAAAAAAAAADAx/9pMAAAAABCBCEACBGEgC4EAAKYMEEIwHr9
    nw8AAAAAIEwQAqoBSASBQgQBAPrJezgGQEAAAAgAAAAAAAAACBEAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAADEgUACJAMAAAA
    AAAAAAAAgH+//8FABAUAiFOEgCAAUgKAEEEACH7/X0cDBFMQIEwQA4gQQQjIev5/DwMAAAAgRFICgRBBAIhChCEwCFOFgMz3
    /28AAEEJAEIEIaAL08WIoEQwAKCfv6fjAgAEACAABQAgBBACAhABCABCBCEAAAAAAAAMAAAgXzYjAcREEAAzYhMQwJDpRAAc
    M6aCAAAAAFDBakBgTNoSsrz9z5l2tK0CuNe/2IumxXkAAAAEAWK0IUD439eAhSHOCQCf/PeBarQ/QbnT7sltTP83r/5tz9t0
    194BCNH/jOt//3+2M/3OmE60vWLzxGEALERSB4ASYQgAYpQBIAhTxgAhTBsDhDABCBAAAAAAAAEAAAAAAAAIAAAEAAAAGAgA
    wHOAAgAAAAAAAAAAQgAlIAhAlIAAAAECgIAAAQAAAAAAAAAAACBACQAEGCAACAAAAAAAAAAAIECQAoAARA4YQpAZIIhApoAA
    AAAAAABIAAAysl0kCFBAACBE2yIyAAAAAAAAAAAAAAAAAAAAAAAAAQAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAACw7XMjLAQQAoIAAAAAACQgAAgThIDJp891MAQ4BwHCAAAAAAAAAKD3/8kwAAAAAEIEIQAAEAAAAEAAAoAQQQjI
    fv5uhgAAAAAgRAACAAAEAAACAAEAiOxyCAQAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAATIABMAAmIAAAIAQA
    AAAAAAAAAAAA3///w0IGJSAIk5aAKERaAoASZQnYbPxeBQKAURAgBBACAABJCAB6/h0HAwAAACBEEAKAMEEIyEKEISAKE4SA
    zeP/ZyAAAAAAQgQhIAJAAAAAQBAAhJm+p8AAAAAAAAAAACAAEAACAAEAAAAAAAAAAAAAAAQAACAONoMCAEAQAAMAAAAAAgQA
    ABI7JAIAAAAA0Mh7BWBE20KWsm2L+XakbQCI1/eEi6PuCQAAEAAAYtQhAPjfl8ANAsYAAAhgRgDK9D2DmdPtg+1M/yai/m3+
    3DaiHgAI0/6E6Fa/A74b/e6ZSvQ9Y4IAIQAgRFRnghJhDwBiBCElCFPHCCFMGwOEECEIAAAAAAAAAAAAAAAAAAAAKAQAAKAQ
    AECNUwIEAAAAAAA1BABCJAEACBkEACAAAAKA8UEIoAioHAAAAAAAAAAAAIAQAQAAAAAAAAAAAAAgRNIGgJhJCpjCBCkgqNHl
    lYwjzwsAEAALAAKEMQCYUUSAKETWAAIAQAAAQgAlIAgAAAAgBBACghABAABCBCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEE
    AAAAECAAAAAAAPj9/x8uREAAgBBBCAgGBAUAAAAEAKCi7wEAACQBAEAAAAAIAQQAwKb/TSAAAAAAQiQhAAgTpIAvRAAAgDFB
    CIh+/3+GAwAMACBMEAK6Ms0eiMKEJyC6+fs6DEQEAIAAEAAQQAQAAIADAAAAQAgAAAAAAAAAAAAAAAAAEAAAAAAQCLoXESAg
    BAAAAAAAAAAAAADfv//DQgQhIAjQgAAgRBQCgBFxC0h+//8H42xjACBMGAKAAAEEAH7//48DAAAAIESYAoCwQQrYQoYJIAgR
    hMXs9//vsBBACggAAAAAiBFkAChEEAKC3f+m4UIEBAAIEAEAAAQAAIAAZQgAQAAAAAARAAAAAAAAAFMepgH81lsPg2AyEMg2
    r/kAXr5nwAAAAADg/fcfLkRSAoIQQAAAAIAAAAgQAADA/9/5MAg0BQFCAAAAABAAACDn330wAAAAAEKEIQAIEwIALEScAoIQ
    QUzI/P+/DxuR9IAhTBADgBBFHJBAAAAAiM1zOgZEUACAAgoAAEIAICAAEYAAAAAAAAAAAQgAAAAAACDhYxIAToABMgw+BQFo
    ogSCQkDiCAAAAAAA////wUIAAIAKASUAoETSD4DSeWtI/v//hyNgcxAgRAACgBBBBAh+/9+PAwAAAKRE2heIAEECgEAAgAAJ
    EYSA7vf/czgAIAAAQoQBACjRzIQjRdsKrls+r2FCZCEACREQACJGugKCEEEoAEIEEAAAEBAAAAQAAAASOiUB0JUZBIOgQxAA
    AoFoENY+JcEAAAAAgMjKAuBn3+qnsf3PmnKkPQD43//PjaO/WQADEAQBctUlQPjfl4AJI4/5AJh914Batr0A+N/vvO1c/7am
    /2/f2iSAvwkI0f6A7X///7Y7/b/Y/ve/97Lc+xkiTNAHghJ5KyBKBAAAKNPGAKFMHwKUMCEJEAAAAAAAAAAAAAAAAACAOBQA
    QAIcALPIYyIAAAAAAN//78FAAAAAAAAAAAAAAAAAAAAAAHq+ng8BAHgACAAAAAAAAAAAbv+/DwMAAAAgRBACgDBBCPgCgAgA
    CBGEgOn///+4EEEICMIEISALEYSAIESQAqKNrLdDAABAAAAQAAAAQBAAgjAAAABCBDAAAAAAAAAAAAAAEhonA8AAAADDYFMA
    QAFAQAAQGCYCAAAAAPj9/z8sRNoChDBhCJjC5CkACZWnhOj3//8wSzwmAWIUIAAo0QQA4P///zgAAAAASqQ5BAkR5IAhRJIC
    ojJNX8j+//+PC5GUAChEEAKAEMUNiMr2bWDS/Xs7BEQQAJAQYQkEQgQhICgRhAAgTFECAAABAAAAAAAA8K1jPkANhQEwHraE
    wRD42Abg7WsqDAAAAIBfv//BQiQlIAgTFIAJQBICgBJBCkA++v8PQsBzECBMAACAAAAAAH7/34cDAAAAoERaAoAwQQj4QgQp
    oAoThIDNt/9/kDBJCYhCACEgKNP/iOhN3zO+37+3Y0JAAQAokYQAgEQAAIAwAQgAQgQwAAAAAAAADAAAAAa6BQLEUBEAoeBT
    AAAyQAAATHTkAgAAAADw//8/DERSAoIwSQmYQkApAAgBBIDg9/99MAC8BQAABAAACAAEgOD37/04AAAAAEKkJQAIG4SALUQQ
    AIowQQjIfv//DwuBlAAgTFACvhFdj8hCJC1g+v17Hw5EEACAEEAAIGIAISAIE4IAAEQCAIAQAAAAQAAAAODlczpIToUFMgg2
    FwASYAQEUGxrIgAAAAAAhC5tAEa1NXILkyaQKURaAoDadQ+ZLMKYBBAAAABgXpkjhBptCxgoshwBgABjAKhE3xOAuF0e2MbU
    b2HqU+6cCQBDA4AQ7U/Y/tV9YyvT/4DpTNsiNgAQCABAYGFAaJHmAABEAACAMG2NEcK0IUAIEYYAAAAAAAAAAAAAAAAAABCg
    cgAAAICBAIAYBgAAAAAAMOjzEAIAQAAAAAAAAAIAAAAAAAAAgObPATQAAAEAAAAAAAAAAABg59tVMAAAAAAAAAAACBEEAC4A
    CAKQAEEAABz4PAAAAAAAIEQQAgoBRAQARgQhYAKB8gImRFQCAAQQAQAAAAAAABAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAABAA
    AgAAAFAEAAAAAAAAAAAAgF9/r+AAAAAACAEEACAABAAAEAAAAADqnAAAQBIAAAAAAAAAAAAAev+eCgIAAgAAAAAIgBBBAIhC
    QCAAABOEAOy37ycAAAAAAEIEIcAAAAQAKEQAAoJYrgHBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAIAACB
    qFsQAAAAAAAAAAAAAAAAAEChUwIEBAAAABAAAABAAAAAAAUAAMSi7wEAAAAAAAAAAAAAAAAAqMb7BzAAAAAAAgYhAAABAAAA
    AAAAgAgAAAAYYAQAAAAEAAAAAAIAAAAAAAAAAQAAbQIABAAAAAAQAAAAQgQhIAAAAAAABAAAAAAAAAAAAAAAQAAIBAAAAAAA
    AAAAAAAABAAAAAAAAAAAAAAf/yfDAAAAAAgBgIAAAAAAgAAAIEB8+p4GEIBzECBEEAIIAAAAAFz+mg0CAAAAIEQQAoAQAQAA
    AgABAAgThIAMgK8CAAAAAABAAAAAAAAAACBEEAICXrmHwQAAAAAoEIQAAgAAAAAAAQAAQgQgAAAAAAAAAAAAAAAAAADABBgA
    gwACAAAAAAAAAAAAAAAAAADw6XsbDEAAAIAQQQAIAAAAAAAAAADAx+9lMAKoBAAAAAAAAAAAAMCm780AAAAAAEKEoQAJE4SA
    LEAQAIAQSQjIWNh+AggQEAAgRAACCAAAAABCBCUgWoFzCAQAAAAAAAAAAAIAICAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABIAB
    IAAiAQAAABQAAAAAAAAAAAAAHjomwAAAAAAAAAAAAAAAAAAAAAAAePkcBgAAQggAAAAAAAAAAABI+JIPAAAAAAAAAAAAAAAA
    AAAAAAAIEYSAQAAAAAAAAAAAAIAAAAIAAAAAAAAAAACABkIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQCKHSAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAACCAYgAAAAAAAAAAAABClCVgCFOGmCBAWgCAEmEICAQCgAAAAAAAIEQRAgAeQAQIEAAAAIAAQACgRFoCgBBF
    ChhCBAEgClGEig0AAACAEEkJEMqUIWAK0cyQqUTZAiYIAIAAAAAAAAgBBAAgAAAAgBAlCABKtCFBABGAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAIACAAIAAAAAAAAAAAAgRBACghBBAAhCBAEACBGkAIChzEEAghIEAQIAAAAIQIaACAAECAAAIAAAQgQhAAAA
    AAAgTBACohBBCMgAgAQACAFAAAAAAACAEEUMiEJEZQACAAAAIEVQAgIAAAAAUgShIAgQgAAgRBADADABAAAAAAAAAAAAAAAA
    AAAAAAAAABRWHABgQDMCAAAAAAAAAAAARAQMAAgRFAEgAZAAgF55CwEAQAAAAAAgAAAAAAAAEAEBAAAAAADwyHsIoGHTKIAS
    SYaQRkYrIOnd9g0BAAAAAADBAAFCtC8gCMBpAKBE1yMGAAAAAAIEQAAIAAQAAAAAAAAQAAAATqAQAAAAAAAAAAAAAAAAAABA
    AAAAAAAAAAIAAAAAAAAAAAAAAAAAABIAoEYbArIQACAARgAhAClVpwAJAAQBBAAAAABChAAACBGGgAAAgAAAADAAAAIGKQAA
    kQAALQQRIIIQQSyYAAAAAABQFAAgRHAKrhBFDphClCkgAAAAAAAEAACAEEEIAAAEAAAIU4QAAAQZAIAQAQgAAAAAAAAAAAAA
    AAAAAAAIAAAAABAAAAAAAgAAAAAAAAAAAAAgBAAA0IYQKUQZIoBwbYvYCnQSBQAAAAAgTAkCgBItgJgAgAADAEBiBCREEAqA
    EMECmEIEKWD4UaeMDQAAAJAQZAgIYPSBognTxwCpTJkCJgAAAAAAAAAACABCACBEAACCGGEIEECQAAAIEYIAAAAAAAAAAAAA
    AAAAAACAAAAAAIKBAAAAAgA=
    """

    private static let enBase64 = """
    AAAA8P//v9ttr/z//+373y7////72fLMd/9XNq+/8v//v59jjfT/e+X/n2ff/375L/bZ/7///v99cxCAgc99v/z3/+3732//
    vT7qTLZPdbZUJrJgEx1lg8lkKgEAAOAZ1wCfa1757//I///f/PjcFtfmkex8r+Tue+X/928R4zDYbfPK/7/ffve99v//P8Ae
    7/z+ewQgAAL///+7/v/a/7/f/n9dVZFmk/8+p0RkI+W/32ud2RoDAADA/7//KpIuEoAEgYggCPz3/Q8ECAAAAACICMLAv/+v
    IoAgAAAAgIggjEQEAQMCCAL///4DABIAAAAAIoIkQlmMgZgkK/j/Pw4iQAARQAAAAARAXaqHAAAAAAAAgP9/v1UEGCAyySMU
    QBT47fdbABIBIoIk8tvvlT98HwEAAGB/3ysRYRDJCIRARAgF/v//lwjgAQAACEQEQQQgiAMxeTb52fcQRAABAAAAAAAAgCNc
    R0QAAAAAAAD//f6LSLJIaLIFNpM88v//v4gkCURkSCUjyCJ//v+LCKJARAAAIoIgEhEEo4ggBfz/+y8ySQAAABCoCMJYZTdW
    IIME8N//gowgAUQECQQAAABXfVQACAAAAAAA3Hn/dJHkk+42j/3n++X/1201aR6Zz7NKZpRG+n5dFgEEge03pvz/++023yP/
    /3/j7/XDb75XAAAg8P//v//+vv3ue82r1xVZSTb57/dKbXJnfv+dMBkgMwAAAHz3+C8iCQAFQAAIABDAd4/fYvM8EggAgIgA
    APytvQoACAIBAQCICIJIAABAIAAg8NVvPQQAAAAAACAiiiKXgQiYTCOKt4+DAAAAEBkAAAAAAAAEAQAAAAAAAAD4z/dbZJJH
    AAAJEAEsgN9+v0AESSAz3yK7bV75y/cZAAAEAIAAEhEEkYggiEREc+S/3y8RSQQAAABARJBEJpuVEhgEoL5/lwEAACAiSCAA
    AACYwJVBIAAAAAAA8P//t4gkiQQiCSAiSAL///8LCYIAAAAAIIMg8P//twAgCEQkACAiiCAR0RSICKPI/7/fEpMgAAAAgYgs
    jpRGYeA/z2v//+4DCABAZBAAAAAA8IXvCQAAAAAAAMC5308XeVapbPPYfp5X3nv8Fpvklfl8rwUEQeCkRAUBQRCI7PLI/79f
    bvO98v//v+9+f0xme00AAAL//3/7///b7Z/fEDAcEFNkk4ggAEwEYyQCCCIRURACAADAf6//AAAAAAAAAAAAAPz6uwmAAAAA
    AAAAAADAfq/fAIIAAAAAAAAAAAAAAAAAAAL/774DAIAAAAAAAAAAAAAAAAhAAGz/ugACAAAAAAAAAAAAABAAAAAAAAAAgP9/
    /0UESSAQAAABQAL46/dLQRAEBgAkEJHlkb9/t0UAACCiCAARQRiJACBARBAE/v/9FpEEAAAAAEQEQeQ7myuBQRL4+ncbAAAA
    IoMkAAAAgAx0KwAAAAAAAAD///+LSLJIZpHEbvP98v//v7ksr0wECaQiCAD///+KCILAZB5T/vf9EpFPkSggDvz//y82yQEA
    AACACILIZjlXMqO89v/vqohgAEQECQQAAAB/+V6aBAIAAAAA/v//t5Nukf/+FUBACOC/330QSBABgABAQBQE/v28FxAAAAAA
    AEQkASQymyKRSQT4//fffLdHAAAAEBFEkP0ojEQCmOD/12ERgACICAIAAAAAupy8EAAAAAAAAPz/+68iSSKRTR75//fLf///
    IpIksPvvtYgkqvz3/yoiCCKxeV6JCIJIRBAAIooo8v/vv8gkiQAAQCAiCCL33XzZz/fa/79nIoIgEhkkAIgAAHxn8yMyCCEA
    AABw73/V5ZpfOps98v/vtZUc39xueWU/zyqReUbpwnFURBAGbrq88t/Pl/t8r/z//8//32Wd3V4BAIDA///f7vv78r/vlb/f
    10WE8eR/3yu1Kaj57fNQZBjkAAAA8P3/v0ggCwQCEyAACAB//f6rCZIAAIAAMtI80sf/uwAAAkAEAKAiDCIRQBSIAAJAX78/
    IpMsAgAAgIggiFRWdaUyyyp/vg4jAABAAIAAAAAA0LylBIAAAAAAAAACgAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAhAIA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIoMEAAAAAAAAAAAAAAAAAAAAAAAAAADA////IpIsEtnlkdt8
    //z//28iywPZWRaJKILIv3//IoAg0NvvlZ1grtymc+U3nyv///+LzvMIAAAEoqMs8tvPl/t8r/3/uy4iiCCRQRKBCADAVz8X
    IoIAAgAAgP9//0UUSSQyySKRSRL47/9PRDJEKoI0cNuvlz/+3wEAQCBiyisRwRCJCKJIRDBG/v/9M5lmEQAACEQMYeC23yv/
    +Xb57/dfRKAEIoIgAAAAgC9eB0QwIAAAAAD+//6LCJJIJJJEAoIM8P//v4okCUQEWeC3/y///v+KCIIAQAAAKsMgEhFEoIgg
    jPz/+y8QSQIAAACICILIZzVe4rPs8pfvmoAAAkQGSQQAAACX7caALrYJAAAAnHv98rntn8omj2TnWWU/3WclXRqYzqNAYIwG
    vnRdFTAEgcgmDfz3++033wf//38DKPHIf7NXAAAg8P//t89+jv3/ew2QAgARYQaIAABAZBIGopJIcBkFMQAAAHj/egwAAAAA
    QAIIACDA96/zAAAAAAEAAAAAAny9+woAAAABAAAICAIAAAAAAoIAwNTnFwQAAAAAACAiCAAABAAAAAAARAMBIAIAAgAAAAAA
    AASEgQEAAAAAAAB47/VfRJAAIoAAAJFkke1d1wQkQWAgAQARQRLh63UVABAAIAKIUBHEkIwgAOxneuXe308ESAAAAABARBBE
    bLu9AhgEACReBwAAAAAyCAAAAACIQAMEAAAAAAAAYITjAgAggEQmSQAAAAAMOS4BCAIAAAAAAoIg8JHnAwAAAAAAAAACAAAB
    AQAIAAAAAqgDIpMkAAAAAQAAAAQAAGAyyCIbIAYACAAABAAAAIAAQ4SBAAAAAAAAAOC732sRQRKITJJARJgA9vv9EJAggaw4
    CUQAAYCDlgMBQBCIEIJARBIMLuIJ0JWGCPZ+v2WmeQAAAAAZYR64zeZAZBACvn+9FBEEkMggARAEACAAAAARAQAAAADAe6/T
    IIAgFAAEgAAAAPz4/wQAAAAQAADICIPAFr6LAAAAEBAgEIgggAQEAQAgAADY+TYJgAAAAAAAAoAAUAAAAAgAAFDyGSQACAAQ
    AAAAAASAAAQAIpoAAg==
    """
}

/// Битовая маска допустимых триграмм одного языка.
struct NGramSet: Sendable {
    private let code: [Character: Int]      // символ → индекс (0 зарезервирован под «начало слова»)
    private let n: Int
    private let bits: [UInt8]

    init(alphabet: [Character], base64: String) {
        var map: [Character: Int] = [:]
        for (i, c) in alphabet.enumerated() { map[c] = i + 1 }
        self.code = map
        self.n = alphabet.count + 1
        self.bits = [UInt8](Data(base64Encoded: base64, options: .ignoreUnknownCharacters) ?? Data())
    }

    /// Все ли символы строки принадлежат алфавиту языка (регистр уже приведён к нижнему).
    func isPureAlphabet(_ s: String) -> Bool {
        !s.isEmpty && s.allSatisfy { code[$0] != nil }
    }

    /// Встречается ли сочетание в языке. Символ вне алфавита (цифра, пунктуация) делает
    /// сочетание невозможным — это и есть сигнал «набрано не в той раскладке».
    func allows(_ a: Character, _ b: Character, _ c: Character) -> Bool {
        guard let i = index(a), let j = index(b), let k = index(c) else { return false }
        let bit = (i * n + j) * n + k
        let byte = bit >> 3
        guard byte < bits.count else { return false }
        return bits[byte] & (1 << UInt8(bit & 7)) != 0
    }

    /// Все ли сочетания слова возможны в этом языке (слово берётся с маркером начала).
    func allowsAll(_ word: String) -> Bool { !hasImpossible(word) }

    /// Есть ли в слове сочетание, невозможное в этом языке.
    func hasImpossible(_ word: String) -> Bool {
        let chars = Array("^" + word)
        guard chars.count >= 3 else { return false }   // короче двух букв судить не о чем
        for i in 0...(chars.count - 3) where !allows(chars[i], chars[i+1], chars[i+2]) {
            return true
        }
        return false
    }

    private func index(_ c: Character) -> Int? {
        if c == "^" { return 0 }
        return code[c]
    }
}
